platform :ios, '8.0'
pod 'AFNetworking', '~> 2.3'
pod 'Mantle', '~> 1.5'
pod 'Overcoat', '~> 2.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'XLForm', '~> 3.1'
pod 'JNKeychain’
pod ‘Reachability’, ‘~> 3.2’
pod 'ApIdleManager', '~> 0.0'
pod ‘LTHPasscodeViewController’, ‘~> 3.7’
pod ‘ABPadLockScreen’, ‘~> 3.4’
pod 'FMDB', '~> 2.6'
pod 'PLCrashReporter', '~> 1.2'
pod 'SWRevealViewController', '~> 2.3'